# This is a basic workflow to help you get started with Actions

name: Lab - Daily

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  daily:
    uses: ./.github/workflows/lab.yml
    with:
      config-prop: daily-lab

  release:
    uses: ./.github/workflows/lab.yml
    with:
      config-prop: release-lab

  feature:
    uses: ./.github/workflows/lab.yml
    with:
      config-prop: feature-lab
